### PR TITLE
Updtcommittee

### LINKED ISSUE #7: Updating Committee on the website
After the discussions regarding the advisory board, we need to update the website.

One idea discussed with @medusamedusa is to have the Peer-review committe to be displayed in a separate page, or somehow being part of a box that expands when someone clicks in it. More Ideas @omarcostahamido ?

In any case, I believe we are already safe to update the advisory board and include the organizers to the homepage?

### PR DESCRIPTION
**Pull request by omarcostahamido**
- this fixes #7

### CODE REVIEW

**Review by medusamedusa — APPROVED** [review]

**Comment by omarcostahamido** [comment]
thank you @medusamedusa !

**Comment by medusamedusa** [comment]
Hi! Did I do something wrong? I read "medusamedusa" restored the uptcommittee...

**Comment by omarcostahamido** [comment]
hi @medusamedusa !
great question. So, what happened is that 
- we created this `updtcommittee` branch to work on these changes, 
- then I made the pull request, 
- you approved it, 
- and then I merged it and deleted the branch `updtcommittee` because we no longer need it.

For some time after deleting a branch you can restore it, and github will show here a button to do so. As an alternative, on github desktop app, if you still have the branch there, and you probably did because you were reviewing it last time, then the last button on top instead of being called `fetch changes` is called `publish branch`. When you click this, it will bring this branch back to github. And that may be what happened here. This doesn't cause any change to the live website because only `main` branch is reflected on the main page, and this branch is protected 😄 
But if you wanted to make some new changes and propose them to be merged on main, I would reccommend creating a new branch from `main` instead of reusing an old branch. Hope that helped clarify it!

I'll go ahead and delete the branch again here.

Oh, and if you also want to delete the branch on your computer/github desktop, make sure that you are on that branch and then go to the menu branch > delete branch.

**Comment by medusamedusa** [comment]
Yes, makes sense — I clicked “fetch origin”. Sorry :(

**Pull request merged**
